# This workflow will build a Swift project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-swift
name: ci

on:
  push:
    branches:
      - main

jobs:
  build-and-test:
    name: Build & Test
    runs-on: macos-latest

    strategy:
      matrix:
        device: [ "iPhone 16", "iPhone 15" ] 

    steps:
      # Checkout the repository
      - name: Checkout code
        uses: actions/checkout@v3

      # Set up Xcode
      - name: Set up Xcode
        run: sudo xcode-select -s /Applications/Xcode_15.0.1.app

      # Run Unit Tests
      - name: Run Unit Tests
        run: |
          xcodebuild test \
            -project tiktoc.xcodeproj \
            -scheme tiktoc \
            -destination "platform=iOS Simulator,name=${{ matrix.device }},OS=17.0" \
            -enableCodeCoverage YES  # Optional: Enables code coverage

      # Build the App
      - name: Build App
        run: |
          xcodebuild build \
            -project tiktoc.xcodeproj \
            -scheme tiktoc \
            -destination "platform=iOS Simulator,name=${{ matrix.device }},OS=17.0"
